### PR TITLE
Create fibonacci.py

### PR DESCRIPTION
**Pull request by Bouh**
Create function for get fibonacci in python.
@JazibJafri

### CODE REVIEW

**Comment by jazibjafri** [comment]
@Bouh rename the file to follow the guidelines.

**Comment by Bouh** [comment]
> @Bouh rename the file to follow the guidelines.

Sure, it's done 👍 
@JazibJafri

**Comment by jazibjafri** [comment]
@Bouh thanks for the PR. It is accepted, and I will merge it, but if you can add the short description before that it'll be a great example for others. Thanks.

**Comment by Bouh** [comment]
An description of what the fibonacci script in the file in comment?

**Comment by jazibjafri** [comment]
Just a single line comment `this function returns the fibonacci series` or something like this. Check out the Readme.md or src folder for an example.

**Comment by jazibjafri** [comment]
@Bouh Thanks for the PR! :rocket:

**Review by jazibjafri — APPROVED** [review]

**Pull request merged**
